### ISSUE TITLE
Data Migrations API

### ISSUE THREAD

**Issue by aristath** [Yoast/update-updater#4]
Plugins should be able to easily run database migrations, so that update and rollback could be performed not only for files but also for data.

Yoast already does this by having a migrations library:
https://github.com/Yoast/wordpress-seo/tree/trunk/lib/migrations
https://github.com/Yoast/wordpress-seo/tree/trunk/src/config/migrations

If we had a unified process for data migrations in core, WordPress would be able to run the latest available migration after an update or rollback, without the need to store anything about the previous state. That would not also require anything from the plugin author, apart from adding a "migrations" folder.

Relevant Trac tickets:
* [ ] [#32606](https://core.trac.wordpress.org/ticket/32606) Plugin data migration
* [ ] [#36887](https://core.trac.wordpress.org/ticket/36887) Database upgrades should fail gracefully
* [ ] [#49188](https://core.trac.wordpress.org/ticket/49188) Add a check for tables structures
