### ISSUE TITLE
Safe zip uploads and unpacking

### ISSUE THREAD

**Issue by carolinan** [Yoast/update-updater#5]
With the introduction of auto-updates, the update processes are run even more often. So relatively small issues get triggered more often, and with that become a bigger problem. They also now more often run unattended: an auto-update that breaks could lead to quite problematic results.

The goal here is to address most of the known issues related to downloading and extracting update packages, copying files and directories, improve documentation for updates, add some automated tests, and make the update process more reliable in general.

- [ ] [#14781](https://core.trac.wordpress.org/ticket/14781) Allow upload of PHP files as plugin _Status:_ needs-refresh has-patch needs-unit-tests
- [ ] [#15134](https://core.trac.wordpress.org/ticket/15134) WordPress should not try to remove theme's or plugin's directory recursively if the directory is a symlink _Status:_  has-patch
- [ ] [#17301](https://core.trac.wordpress.org/ticket/17301) Keep the connection open when doing upgrades or long-running operations _Status:_ has-patch needs-testing needs-refresh
- [ ] [#20944](https://core.trac.wordpress.org/ticket/20944) Changing plugin filename causes Fatal error on automatic activation after update _Status:_ Needs documentation, has-patch needs-testing needs-refresh
- [ ] [#26626](https://core.trac.wordpress.org/ticket/26626) WP_Upgrader::unpack_package() can overflow path name length limits _Status:_ has-patch dev-feedback
- [ ] [#29408](https://core.trac.wordpress.org/ticket/29408) Symlinked themes and plugins should not be updatable _Status:_ Needs patch
- [ ] [#33571](https://core.trac.wordpress.org/ticket/33571) Improvements for plugin upgrades when disk space runs out (or other write failure) _Status:_ Awaiting review
- [ ] [#34676 ](https://core.trac.wordpress.org/ticket/34676) Optimize bulk plugin updates _Status:_ has-patch needs-unit-tests shiny-updates early needs-refresh
- [ ] [#35217](https://core.trac.wordpress.org/ticket/35217) WP_Upgrader: writes temporary directory name to plugin folder if zip doesn't have directory _Status:_
- [ ] [#36373](https://core.trac.wordpress.org/ticket/36373) Plugin update fails silently when using zipfile without subdirectory _Status:_ needs-patch **2nd-opinion**
- [ ] [#38084 ](https://core.trac.wordpress.org/ticket/38084)Fix Inconsistency Theme and Plugin Update Process When No Package Found _Status:_ needs-patch
- [ ] [#44002](https://core.trac.wordpress.org/ticket/44002) fread(): Length parameter must be greater than 0 - Happens on all updates to core, plugins, themes.
- [ ] [#44118](https://core.trac.wordpress.org/ticket/44118) WordPress performs some unnecessary plugin update checks _Status:_ has-patch **2nd-opinion**
- [ ] [#44418](https://core.trac.wordpress.org/ticket/44418) fs_unavailable while auto-updating plugins _Status:_ needs-patch has-screenshots **reporter-feedback**
- [ ] [#50349](https://core.trac.wordpress.org/ticket/50349) Plugin Update deletes plugin and showing "could not delete old plugin" message _Status:_
- [ ] [#50849](https://core.trac.wordpress.org/ticket/50849) Incorrect action passed to hooks when updating plugin/theme by uploading ZIP file _Status:_ has-patch needs-testing
- [ ] [#51823 ](https://core.trac.wordpress.org/ticket/51823)Native auto updater caused plugin update to fail and disappears plugin from directory _Status:_
