### ISSUE TITLE
Unified JSON convention for requirements and dependencies

### ISSUE THREAD

**Issue by JustinyAhin** [Yoast/update-updater#6]
## Description

Different plugins have introduced compatibility tags (For example, [Elementor](https://developers.elementor.com/compatibility-tag/) and [WooCommerce](https://docs.woocommerce.com/document/create-a-plugin/#section-10)). In the long run, this could become harder to manage.

This issue could be solved by adding a `requirements.json` file in the root of the plugin or theme. The JSON file could be formatted like:

```
{
    "core": "5.7",
    "plugins": {
        "woocomerce": "4.0"
    }
}
```
or

```
[
    {
        "type": "core",
        "version": "5.7"
    },
    {
        "type": "plugin",
        "file": "gutenberg/gutenberg.php",
        "name": "Gutenberg",
        "version": "10.4"
    }
]
```

If the plugin requires another one to work, we could also add another node to extend the JSON like this:
```
[
    {
        "type": "core",
        "version": "5.7"
    },
    {
        "type": "plugin",
        "file": "gutenberg/gutenberg.php",
        "name": "Gutenberg",
        "version": "9.0",
        "requires": {
            "type": "plugin",
            "file": "yoast/yoast.php",
            "name": "Yoast SEO",
            "version": "16.0"
        }
    }
]
```

## Additional information

@afragen has written a lightweight library, [wp-dependency-installer](https://github.com/afragen/wp-dependency-installer), that takes a JSON config file and can install a suggested or required plugin dependency.

## Related tickets on Trac

- [ ] [#11308 Handling plugin dependencies](https://core.trac.wordpress.org/ticket/11308)
- [ ] [#20241 make it possible for plugins to activate other plugins](https://core.trac.wordpress.org/ticket/20241)
- [ ] [#22316 Plugin Dependencies (Yet Another Plugin Dependencies Ticket)](https://core.trac.wordpress.org/ticket/22316)
- [ ] [#23912 Add Composer package description](https://core.trac.wordpress.org/ticket/23912)
- [ ] [#47285 Better Management of External Asset Dependencies](https://core.trac.wordpress.org/ticket/47285)
- [ ] [#52154 Ability to install site with predefined configuration without Docker or console commands — analogue of package.json for full site installation with exact settings, plugins, themes and their settings](https://core.trac.wordpress.org/ticket/52154)
