### ISSUE TITLE
A mechanism to upgrade and rollback

### ISSUE THREAD

**Issue by aristath** [Yoast/update-updater#7]
When a core auto-update fails, core has long had the ability to automatically attempt a "rollback" to the latest stable release (in the branch that the site is running). Note: for core auto-updates, "rollback" is not attempted for certain failures (e.g. "disk full", etc).

This capability should be extended to be available for plugin and theme updates.

Relevant Trac tickets:
* [ ] [#37301](https://core.trac.wordpress.org/ticket/37301) A way to test plugin/theme installs and updates before applying
* [ ] [#49963](https://core.trac.wordpress.org/ticket/49963) Security of failed update/rollback
* [ ] [#50937](https://core.trac.wordpress.org/ticket/50937) Auto-backup in core
* [ ] [#51816](https://core.trac.wordpress.org/ticket/51816) Implement auto recovery mode during auto update cron (See [Rollback Update Failure](https://wordpress.org/plugins/rollback-update-failure/))
* [ ] [#51857](https://core.trac.wordpress.org/ticket/51857) Add rollback for failed plugin/theme updates (See [Rollback Update Failure](https://wordpress.org/plugins/rollback-update-failure/))
* [ ] [#51928](https://core.trac.wordpress.org/ticket/51928) Provide plugin/theme update failure data to dot org
